Add get method in collection and partition
milvus-io/pymilvus-orm pull request #142
Opened 2021-06-01 09:19 UTC by fishpenguin

Signed-off-by: fishpenguin <kun.yu@zilliz.com>

2021-06-01 09:44 UTC, scsven requested changes

2021-06-01 09:44 UTC, scsven commented on tests/test_partition.py
> +        res = partition.get(ids[0:10])
Add an empty line at the end of file.

2021-06-01 10:03 UTC, scsven approved these changes
/lgtm
/approve

2021-06-01 10:03 UTC, scsven commented
/label ci-passed

2021-06-01 10:05 UTC, scsven commented
/assign @czs007 Need your approval.

2021-06-02 02:20 UTC, czs007 approved these changes

2021-06-02 02:21 UTC, czs007 commented
/lgtm
/approve

2021-06-02 02:21 UTC, merged